language: go
go:
- "1.17"
sudo: false
services:
- docker
env:
  matrix:
  - LIBRDKAFKA_VERSION=v1.0.0
cache:
  directories:
  - "$HOME/.cache/librdkafka"
before_install:
- sudo /bin/bash ./travis.sh
before_script: make setup-ci
script: make test-ci
after_success: bash push_to_docker.sh
