scrape_configs:
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['eventsgateway-api:9091', 'eventsgateway-client:9002']

# prometheus metrics
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9090']
