kafka:
  logger:
    enabled: true
  producer:
    clientId: eventsgateway
    timeout: 250ms
    brokers: kafka:9092
    maxMessageBytes: 1000000
    linger:
      ms: 1
    net:
      maxOpenRequests: 10
      dialTimeout: 500ms
      readTimeout: 250ms
      writeTimeout: 250ms
      keepAlive: 60s
    retry:
      max: 0
server:
  maxConnectionIdle: 20s
  maxConnectionAge: 20s
  maxConnectionAgeGrace: 5s
  Time: 10s
  Timeout: 500ms
pprof:
  enabled: true
  address: localhost:6060
otlp:
  enabled: true