# Those properties can also be loaded as ENV Vars with EVENTSGATEWAY_ prefix.
kafka:
  logger:
    enabled: true
  producer:
    clientId: eventsgateway
    timeout: 250ms
    brokers: kafka:9092
client:
  async: false
  channelBuffer: 500
  lingerInterval: 500ms
  batchSize: 10
  kafkatopic: default-topic
  maxRetries: 3
  numRoutines: 2
  retryInterval: 2s
  grpc:
    serverAddress: localhost:5000 #eventsgateway-api:5000
    timeout: 500ms
loadtestclient:
  duration: 1s
  threads: 1
  randSleepCeilingMs: 500
  randPropsSize: small # small, medium, large, jumbo
