name: Run tests
on: push
jobs:
  client-tests:
    name: Run client tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: make build-dev
      - run: make test
  server-tests:
    name: Run server tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - run: cd server && make build-dev
      - run: cd server && make test
